name: guide
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  pdfx: ^2.4.0
  path_provider: ^2.1.2
  json_annotation: ^4.8.1
  aws_dynamodb_api: ^2.0.0
  # pdfx: ^2.5.0
  # current version pdfx is bugged on flutter >= 3.15 smiley


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  build_runner: ^2.4.8
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/pdf/
    - assets/json/

  fonts: 
    # Add Montserrat font
    - family: Montserrat
      fonts:
        - asset: assets\fonts\FontsFree-Net-Montserrat-Medium.ttf